### ISSUE TITLE
Problem with large bz2 files

### ISSUE THREAD

**Issue by a1an77** [marcelm/xopen#6] opened 2017-11-22 14:59 UTC
I am using cutadapt on large bz2 files and getting processing errors (FASTQ file ended prematurely). When I decompress the files before processing I get no errors. File sizes are around 900M compressed, 3,4G decompressed, holding 5M+ sequences. Running cutadapt 1.14 with Python 2.7.9. Thought it might be a problem with this library

Few sequences make it through, then it breaks with the error.

**Comment by marcelm** [comment] 2017-11-22 15:23
Do you know how the bz2 files were created? Python 2.7.9 does not support concatenated bz2 files that tools such as `pbzip2` create (parallel bzip2). See also [the last sentence in this paragraph in the cutadapt documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#compressed-files).

I cannot really fix this, but perhaps detect it so that the error message is more useful.

**Comment by marcelm** [comment] 2017-11-22 15:30
Hm, it could be fixed by [using the external bz2file library](https://pypi.python.org/pypi/bz2file). See the [note in the Python 2 docs](https://docs.python.org/2/library/bz2.html#de-compression-of-files).

**Closed** 2017-11-22 18:20 UTC

**Comment by kyleabeauchamp** [comment] 2017-11-22 18:25
PS: there's a similar issue in the standard library py27 gzip (https://bugs.python.org/issue23306), which we one is able to work-around by using the xopen external / streaming gzip library.

**Comment by marcelm** [comment] 2017-11-22 18:49
@a1an77 If your problem was actually caused by using pbzip2, then this is fixed now. If there is some other problem, please re-open.

@kyleabeauchamp Hm, interesting. But you’re right, since we’re delegating to an external gzip or pigz, this should not a problem. In any case, if it occurs, there would be a stacktrace, so we don’t have to worry about silent data corruption.

**Comment by a1an77** [comment] 2017-11-23 15:19
It is indeed fixed, many thanks
